micron_sonar_node:
  ros__parameters:
    debug: false
    baudrate: 115200
    udpPort: 4000
    udpServer: ""
    port: "/dev/ttyUSB0"
    max_distance: 10.0
    min_distance: 0.0001
    frequency_out: 15.0
    gain: 0.45
    speed_of_propagation: 1500.0 #1482.0 # in water
    angular_resolution: 3.0
    left_limit: 135.0 # no difference when I set them...
    right_limit: 180.0 # no difference when I set them...
    # speed_of_propagation: 343.0 # in air
    # angular_resolution: 1.0
    # low_resolution: true

    # resolution: 0.1 # don't touch it
